# Generated by Django 4.1.6 on 2023-02-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Plan',
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={},
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='name',
            new_name='item',
        ),
    ]
